### ISSUE TITLE
kubeconfig 文件是在哪里呢

### ISSUE THREAD

**Issue by valiner** [ben1234560/k8s_PaaS#11]
kubeconfig 文件 没在～/.kube里面

**Comment by ben1234560** [comment]
需要再具体些，或者指明到哪一章节哪一块了

**Comment by valiner** [comment]
就是dashboard通过kebuconfig的方式连接，这个config需要自己生成对吧？

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月22日(周三) 晚上7:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ben1234560/k8s_PaaS] kubeconfig 文件是在哪里呢 (#11)




 
需要再具体些，或者指明到哪一章节哪一块了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ben1234560** [comment]
如果你指的是第四章节访问dashboard后，根据页面说的配置kubeconfig。这里是只有一个集群，而且是在集群上搭建的，本身已经监控了当前集群的各种信息。
根据md文件内容，点跳过即可，后续也会接入越来越多的内容。

**Comment by valiner** [comment]
现在我想在集群外部使用lens工具接入集群，发现找不到config了，网上都说在~/.kube里面，刚找了发现没有这个配置文件。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月22日(周三) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ben1234560/k8s_PaaS] kubeconfig 文件是在哪里呢 (#11)




 
如果你指的是第四章节访问dashboard后，根据页面说的配置kubeconfig。这里是只有一个集群，而且是在集群上搭建的，本身已经监控了当前集群的各种信息。
 根据md文件内容，点跳过即可，后续也会接入越来越多的内容。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ben1234560** [comment]
这里是token认证，kubeconfig你可能得单独生成

**Comment by valiner** [comment]
好的，谢谢🙏
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ben1234560/k8s_PaaS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ben1234560/k8s_PaaS] kubeconfig 文件是在哪里呢 (#11)





 
这里是token认证，kubeconfig你可能得单独生成
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
