### ISSUE TITLE
除了10.4.7.11，其他虚机无法联网

### ISSUE THREAD

**Issue by xinzhuxiansheng** [ben1234560/k8s_PaaS#12]
按照doc，包括ip段设置一样，在配置11机器上配置 DNS，然后将其他机器的dns换成11，是都可以访问网络的 (当然这也符合预期)。 
后来，我关机睡觉 ，第二天，出现 只有10.4.7.11机器能上网，其他机器，只要DNS1设置为10.4.7.11都不能上网，需要将dns1换成 10.4.7.254 才能上网 。
这个跟博主的doc 预期不一致，目前我也不清楚，不知道博主能否解答下 。

**Comment by ben1234560** [comment]
虽然你已经加群且解决了，我还是在这里回复下。
目前出现过的解决办法：
1. DNS重启
2. 检查网络是否连接，如果涉及本地hosts或者其它的可能还需要清缓存
3. 如果是可开放的机器，可以提供下IP和密码给我，我如果处理完跟你说结果和方法，然后你再改密码就好
