### ISSUE TITLE
强烈建议标注出 systemctl start named的与众不同 :)

### ISSUE THREAD

**Issue by xinzhuxiansheng** [ben1234560/k8s_PaaS#13]
在左右节点机器都将DNS1配置为10.4.7.11，这时 10.4.7.11的named服务显得格外重要，并且需要提示用户，named应该时刻保证运行状态。这样以此保证其他节点机器，可以连接外部网络

**Comment by ben1234560** [comment]
感谢提议，已补充
![image](https://user-images.githubusercontent.com/51939568/138599792-4e9462d3-71f3-433a-9f11-0672693ab678.png)
