### ISSUE TITLE
nginx 安装补充  

### ISSUE THREAD

**Issue by nangongchengfeng** [ben1234560/k8s_PaaS#16]
`yum install nginx nginx-mod-stream  -y`

安装nginx时，建议 安装上 nginx-mod-stream ，不然在添加
stream {
    upstream kube-apiserver {
        server 10.4.7.21:6443     max_fails=3 fail_timeout=30s;
        server 10.4.7.22:6443     max_fails=3 fail_timeout=30s;
    }
    server {
        listen 7443;
        proxy_connect_timeout 2s;
        proxy_timeout 900s;
        proxy_pass kube-apiserver;
    }
}
可能会报错，会显示没有这个stream模块。
感谢楼主分享

**Comment by ben1234560** [comment]
非常nice的建议和解决方法，如果感兴趣可以修改md文件，并提交以便记录你的贡献者身份（默认情况下本周会将你的内容更新到md文件，如图）
![image](https://user-images.githubusercontent.com/51939568/150457139-1a4cf340-798a-43ce-a57d-92c38f92a45f.png)

**Comment by nangongchengfeng** [comment]
已经提交贡献，但不知道方法是否对不对，可能需要您的指导。

**Comment by ben1234560** [comment]
抱歉，没有收到你的Pull requests，请确认下
![image](https://user-images.githubusercontent.com/51939568/150628741-17f9c70e-876d-4aae-b79a-e7dddbfc33d8.png)
