### ISSUE TITLE
建议添加一下时间同步

### ISSUE THREAD

**Issue by haiya512** [ben1234560/k8s_PaaS#31]
如果etcd服务器时间不同步的话，etcd组成集群有问题，执行`./etcdctl cluster-health` 总是报错，后来date一下，发现时间不一致，在执行之后就OK了

具体命令
```bash
timedatectl set-timezone Asia/Shanghai

timedatectl set-ntp true
```

**Comment by ben1234560** [comment]
非常感谢你的建议，是否考虑pr到该项目？
默认24小时后将进行代替pr，内容将@你的github账户作为原创贡献者

**Comment by haiya512** [comment]
可以的，怎么PR？我clone再提交？

**Comment by ben1234560** [comment]
可参考这个方法：https://github.com/ben1234560/k8s_PaaS/blob/master/CONTRIBUTING.md
没有其它pr的限制，表明内容即可

**Comment by haiya512** [comment]
感谢楼主的邀请，已经提交PR。

另外，感觉楼主可以把一些坑点的解决方案写出来，最近遇到了一个坑，我在用桥接模式，IP跟你的不一致，在对etcd做CA认证的时候，IP没改过来，导致集群启动报错。  
除了重新生成证书，再用新的证书启动之外，有没有其他的解决方案，我最近正在看。

**Comment by haiya512** [comment]
感谢楼主的邀请，已经提交PR。

另外，感觉楼主可以把一些坑点的解决方案写出来，最近遇到了一个坑，我在用桥接模式，IP跟你的不一致，在对etcd做CA认证的时候，IP没改过来，导致集群启动报错。  
除了重新生成证书，再用新的证书启动之外，有没有其他的解决方案，我最近正在看。

**Comment by ben1234560** [comment]
非常感谢你的提交，提交已合并，详见[链接](https://github.com/ben1234560/k8s_PaaS/commit/00fc9c0f210b16d4048ef8104e910e68781eb848)。
我们想法一致，目前就是这么做的，遇到坑点会同步解决方案，也会同步整理其他同学提供的解决方案，不过踩坑不多，暂时也不够全面。
该问题已同步，24小时后将关闭该Issue
