### ISSUE TITLE
第五章jenkins build项目的时候，提示不能链接10.4.7.200:443，请问如何解决

### ISSUE THREAD

**Issue by shamo666** [ben1234560/k8s_PaaS#34]
我的harbor只能http访问，没有配置https访问，jenkins构建项目的时候默认用https访问harbor，发生报错：failed to do request: Head "https://harbor.od.com/v2/base/jre8/manifests/8u112": dial tcp 10.4.7.200:443: connect: connection refused，请问如何解决

前提：http://harbor.od.com各个机器都能正常访问，各个机器和jenkins容器docker login harbor.od.com也能成功，不过访问443端口确实失败，因为harbor没有配置https访问

![error](https://user-images.githubusercontent.com/35161796/231074900-c5054543-1011-4be4-a472-36d560953089.png)

**Comment by ben1234560** [comment]
不确定为什么你那边会指向https，或许你可以在这里进行修改，将harbor.od.com补全变成http://harbor.od.com，这样应该就可以指定http进行底座拉取构建。
![@QA5B8`1` $6MF@H`K9LS97](https://user-images.githubusercontent.com/51939568/231087786-ae2b15f5-e509-4fc0-91a6-ce63d43317e2.png)
