### ISSUE TITLE
照着教程装  到supervisor status这步就报错了

### ISSUE THREAD

**Issue by kileroppo** [ben1234560/k8s_PaaS#36]
![E HKNJ7Q13OP UHYI4C(53R](https://user-images.githubusercontent.com/26271091/232299351-8ef84bfd-8fa9-4d88-a2a2-1fd8245445a8.png)
安装到supervisor这里就报错

**Comment by ben1234560** [comment]
可以看下/data/logs/etcd-server/etcd.stdout.log 里的日志信息。一般退出较快是配置文件问题，刚刚拉起就报错了

**Comment by ben1234560** [comment]
你好，有个跟你同期遇到问题且解决的是由于/etc/supervisord.d/etcd-server.ini配置错误。

该问题长期未回复，将进行关闭。
