### ISSUE TITLE
第二章nging启动失败报错

### ISSUE THREAD

**Issue by xzldb** [ben1234560/k8s_PaaS#38]
遇到nginx启动报错出现
Oct 02 00:51:40 hdss7-11.host.com nginx[121227]: nginx: [emerg] bind() to 0.0.0.0:7443 failed (13: Permission denied)
多次确认配置文件没问题的情况下

可以尝试使用
setsebool -P httpd_can_network_connect 1
执行这个命令后，SELinux将允许Nginx进行网络连接，通常可以解决Nginx绑定端口时的权限问题。
ausearch -c 'nginx' --raw | audit2allow -M my-nginx
semodule -X 300 -i my-nginx.pp
这将尝试生成并应用一个SELinux策略模块，以允许Nginx绑定到端口 7443。
进行这俩操作后，可以使nginx正常启动

**Comment by xzldb** [comment]
艹，往后面做的时候发现后面有提到这种问题（我在这里的issue翻没翻到

**Comment by ben1234560** [comment]
好的，那我关闭该问题了
