### ISSUE TITLE
paas开放平台上的多租户怎么做呢？

### ISSUE THREAD

**Issue by glacierck** [ben1234560/k8s_PaaS#4]
如题，在寻找一个干净的paas平台架构，然后将一些nlp服务做成saas服务放进去，做个支持多租户的应用平台。也就是用户可以在平台上注册自己的应用然后得到独立的或者共享的nlp服务资源。

**Comment by ben1234560** [comment]
目前公司产品的做法是以空间为权限管理：
1.每个用户使用自己的模型空间，模型空间可自建多个，模型空间下可以有多个模型；
2.在模型空间下建立模型，以你上面说的一些nlp服务做成saas，你可以将saas开放到指定客户的模型空间下；
3.共享模型也是把整个模型空间共享给指定的用户；

也就是不再以模型为点，操控模型的共享权限，而是操控该模型空间的权限；不同模型空间下的模型也都是单个容器在运行。
