### ISSUE TITLE
第二章最后执行kubectl get pods为空无法打标签

### ISSUE THREAD

**Issue by tianheyi** [ben1234560/k8s_PaaS#41]
按照步骤在安装部署运算节点服务（kubelet）中，执行kubectl get pods后没有看到有内容，也就无法正常打标签。
使用第二章的检查工具也没提示有任何问题。
即便是走完了全部流程，即走完了最后一步安装部署运算节点服务（kube-proxy），还是一样kubectl get pods无内容

**Comment by tianheyi** [comment]
apiserver日志截图：https://github.com/tianheyi/resource-images/blob/main/k8s.png

**Comment by tianheyi** [comment]
etcd日志 https://github.com/tianheyi/resource-images/blob/main/etcd%E6%97%A5%E5%BF%97.png

**Comment by ben1234560** [comment]
复制文字就好，目前看来是通信有问题；
1.是否中途有重启过机器，再用快照复原的，如果是，检查下防火墙之类的，这些会有影响
2.21机器跑下supervisorctl status 查看下服务以及kubectl get cs；

**Comment by tianheyi** [comment]
防火墙全执行过stop+disable，应该没什么问题
[root@hdss-21 etcd]# systemctl status firewalld.service 
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@hdss-21 etcd]# supervisorctl status
etcd-server-7-21                 RUNNING   pid 989, uptime 9:20:56
kube-apiserver-7-21              RUNNING   pid 990, uptime 9:20:56
kube-controller-manager-7-21     RUNNING   pid 986, uptime 9:20:56
kube-kubelet-7-21                RUNNING   pid 987, uptime 9:20:56
kube-proxy-7-21                  RUNNING   pid 23240, uptime 8:19:37
kube-scheduler-7-21              RUNNING   pid 988, uptime 9:20:56
[root@hdss-21 etcd]# kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
etcd-2               Healthy   {"health": "true"}   
scheduler            Healthy   ok                   
etcd-1               Healthy   {"health": "true"}   
etcd-0               Healthy   {"health": "true"}   
controller-manager   Healthy   ok

**Comment by ben1234560** [comment]
参考这里的方法，telnet检查下。给21跟22都加上反代，作为替代方案，估计是版本原因，导致通信异常。
https://github.com/ben1234560/k8s_PaaS/blob/master/%E7%AC%AC%E4%BA%8C%E7%AB%A0%E2%80%94%E2%80%94%E4%BC%81%E4%B8%9A%E9%83%A8%E7%BD%B2%E5%AE%9E%E6%88%98_K8S%E3%80%90%E5%85%AC%E6%9C%89%E4%BA%91%E7%89%88%E3%80%91.md#%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2%E4%B8%BB%E6%8E%A7%E8%8A%82%E7%82%B9l4%E5%8F%8D%E4%BB%A3%E6%9C%8D%E5%8A%A1

**Comment by tianheyi** [comment]
我发现我执行完telnet连不通，然后执行下面发现是配置文件问题。。示例是interface eth0，我改成eth33了，应该改成ens33.。。。太呆了我，我现在把11和12的也改过来了，然后执行kubelet get node就有了，谢谢你
[root@hdss-21 ~]# systemctl status keepalived
● keepalived.service - LVS and VRRP High Availability Monitor
   Loaded: loaded (/usr/lib/systemd/system/keepalived.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2023-11-15 20:54:02 CST; 19s ago
 Main PID: 24589 (code=exited, status=0/SUCCESS)

Nov 15 20:53:56 hdss-21.host.com Keepalived_vrrp[24591]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 15 20:53:56 hdss-21.host.com Keepalived_vrrp[24591]: WARNING - default user 'keepalived_script' for script execution does not e...reate.
Nov 15 20:53:56 hdss-21.host.com Keepalived_vrrp[24591]: Cant find interface eth33 for vrrp_instance VI_1 !!!
Nov 15 20:53:56 hdss-21.host.com Keepalived_vrrp[24591]: Default interface eth0 does not exist and no interface specified. Skipping...33.10.
Nov 15 20:53:56 hdss-21.host.com Keepalived_vrrp[24591]: VRRP_Instance(VI_1) Unknown interface !
Nov 15 20:53:57 hdss-21.host.com Keepalived_vrrp[24591]: Stopped
Nov 15 20:53:57 hdss-21.host.com Keepalived[24589]: Keepalived_vrrp exited with permanent error CONFIG. Terminating
Nov 15 20:53:57 hdss-21.host.com Keepalived[24589]: Stopping
Nov 15 20:53:57 hdss-21.host.com Keepalived_healthcheckers[24590]: Stopped
Nov 15 20:54:02 hdss-21.host.com Keepalived[24589]: Stopped Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Hint: Some lines were ellipsized, use -l to show in full.
