### ISSUE TITLE
删除21节点重新连接后无法访问dashboard.od.com浏览器显示404 page not found  curl显示301

### ISSUE THREAD

**Issue by cyanskyssss** [ben1234560/k8s_PaaS#53]
![image](https://github.com/user-attachments/assets/eae76fb6-fd57-45d0-ab29-4eb312ebb48e)
浏览器 显示 

curl显示 
![image](https://github.com/user-attachments/assets/49bb361f-fc54-40d9-8126-7fc45b820c02)
pods内部报错 
![image](https://github.com/user-attachments/assets/a90ce6cf-59fc-48d3-8ee9-fcb6e4ecfe22)

**Comment by cyanskyssss** [comment]
根据报错我想要重启 kube-state-metrics 
但是发现不存在 
![image](https://github.com/user-attachments/assets/1611ced1-89c2-4d4c-8fa2-f7fe8d891737)

**Comment by cyanskyssss** [comment]
所以我想要去寻找heapster服务 ，但是第四章因为显示不需要做 所以其实我并未 完成heapster服务 ，我也不知道为什么会提醒我没有找到这个服务

**Comment by cyanskyssss** [comment]
最后是找到了百度云里面的heapster.tar load成了docker镜像推送到了harbor仓库，然后重启了supervisor，之后再在 第五章最后的 iptables规则 部分添加了 iptables -t nat -I POSTROUTING -s 172.7.21.0/24 ! -d 172.7.0.0/16 ! -o docker0 -j MASQUERADE  iptables-save |grep -i postrouting 之后成功带着21节点启动了 ，这三步我也不知道哪一步是决定性因素
![image](https://github.com/user-attachments/assets/8191c105-621d-4e3b-9878-b177720b365e)

**Comment by ben1234560** [comment]
看起来很奇怪，heapster不是强制项，可能因为版本变迁。我查了下官网依然没有变化，目前主流还是Prometheus系列
